import { writable } from 'svelte/store';
import type Poi from '../poi/poi';

// We'll be using Maps for all of this stuff since they're more performant (O(1) lookup in state)
// The hashes will be generated by our SHA256 hashing function - See hashing.ts
const pois = writable<Map<string, Poi>>(new Map());

export { pois };
